#!/usr/bin/env php
<?php

$db_file = __DIR__.'/members.sqlite3';

// Prepare SQL
$db = new SQLite3($db_file);
$db->enableExceptions(true);
$db->exec('BEGIN; DROP TABLE IF EXISTS slack; CREATE TABLE slack (username,email,status,active,twofa,sso,userid,fullname,displayname,expiration);');
$stmt = $db->prepare('INSERT INTO slack VALUES (?,?,?,?,?,?,?,?,?,?)');
$count = 0;

// Drop header
$header = fgetcsv(STDIN);
if ($header !== ['username','email','status','billing-active','has-2fa','has-sso','userid','fullname','displayname','expiration-timestamp']) {
    die("Unexpected Slack headers\n");
}

while (true) {
    $line = fgetcsv(STDIN);
    if ($line === false) break;

    foreach ($line as $i => $rawval) {
        switch ($i) {
        case 3:
        case 4:
        case 5:
            $v = intval($rawval);
            break;
        default:
            $v = $rawval === '' ? null : $rawval;
        }

        $stmt->bindValue($i+1, $v);
    }

    $stmt->execute();
    $count++;
}

$db->exec('END');
print("Parsed $count Slack accounts\n");
