#!/usr/bin/env php
<?php

require(__DIR__.'/common.php');

// Prepare SQL
$db = init_db();
$db->exec('BEGIN; DROP TABLE IF EXISTS slack; CREATE TABLE slack (username,email,status,active,twofa,sso,userid,fullname,displayname,expiration,email_norm);');
$stmt = $db->prepare('INSERT INTO slack VALUES (?,?,?,?,?,?,?,?,?,?,:email_norm)');
$count = 0;

// Drop header
$header = fgetcsv(STDIN);
if ($header !== ['username','email','status','billing-active','has-2fa','has-sso','userid','fullname','displayname','expiration-timestamp']) {
    die("Unexpected Slack headers\n");
}

while (true) {
    $line = fgetcsv(STDIN);
    if ($line === false) break;

    foreach ($line as $i => $rawval) {
        switch ($i) {
        case 3:
        case 4:
        case 5:
            $val = intval($rawval);
            break;
        default:
            $val = $rawval === '' ? null : $rawval;
        }

        if ($i === 1 && $val !== null) {
            $stmt->bindValue(':email_norm', normalize_email($val));
        }

        $stmt->bindValue($i+1, $val);
    }

    $stmt->execute();
    $count++;
}

$db->exec('END');
print("Parsed $count Slack accounts\n");
